Adding executable frame
BrunnerLivio/nestjs-unit-test-db-example pull request #2
Opened 2019-10-03 14:02 UTC by tuhlmann

This mainly keeps your code and adds the executable framework for Nest 6

2019-10-03 14:15 UTC, BrunnerLivio requested changes
Thanks a lot for your PR! It looks really got from what I have seen so far! :)

I think we should use TSLint and Prettier settings from [nestjs/typescript-starter](https://github.com/nestjs/typescript-starter/). Reason for that is because users will most likely copy and paste the code from this repo in their project. Most likely they will use the standard of NestJS, so it would be more convenient if it has the same settings and format options.

2019-10-03 14:17 UTC, BrunnerLivio commented on package.json
> +    "@lxdhub/db": "^1.10.1",
We should remove that and all the lines it refers to. That was the project I have used this technique for, but it is not related to this repository ;)

2019-10-03 14:20 UTC, BrunnerLivio commented on src/user/user.repository.ts
> +// export const UserRepositoryProvider = {
Remove this.

This workaround was needed back in Nest 4 for custom repositories.

2019-10-03 15:07 UTC, tuhlmann commented
@BrunnerLivio Awesome, will do the changes.

2019-10-04 07:39 UTC, BrunnerLivio approved these changes

2019-10-04 07:39 UTC, BrunnerLivio commented
Thank so much @tuhlmann <3 :)

2019-10-04 07:39 UTC, merged